lane :release_pod do |options|
  target_repo    = options[:repo]
  target_project = options[:project]
  target_version = options[:version]
  target_desc    = options[:desc]
  spec_parm = options[:parm]
  spec_path      = "#{target_project}.podspec"
  
  
version_bump_podspec(path: spec_path, version_number: target_version)
  git_add(path: '.')


if target_desc
git_commit(path: '.', message: target_desc)
else
git_commit(path: '.', message: 'release')
end


push_to_git_remote



  add_git_tag(tag: target_version)

 push_git_tags


pod_lib_lint(allow_warnings: true, use_libraries:true, verbose:true)

if target_repo

    pod_push(repo: target_repo, path: spec_path, allow_warnings: true, use_libraries:true, verbose:true)
  else
    pod_push(path: spec_path, allow_warnings: true, use_libraries:true, verbose:true)
  end
end